### ISSUE TITLE
More information in readme.md

### ISSUE THREAD

**Issue by ShDis** [TechnicJelle/BlueMapMarkerGenerator#22]
Hi! Could you please provide an instruction how to install & launch this project as website? Want to try it locally

**Comment by TechnicJelle** [comment]
It works just like any other Flutter project, really.
Once you have the repo downloaded/cloned, run `flutter pub get` to download all the dependencies, and then run `flutter run` to run the project. You may need to then type a number to select your browser.
I guess I'll add this to the readme, too.

**Comment by TechnicJelle** [comment]
If you start looking through the code, please don't judge it too harshly :sweat_smile:
I am aware I should use a better state management solution than just passing `setState` around everywhere, but my primary goal was to just get it working.
A refactor to make it use Riverpod is planned, however, it's probably pretty far in the future..
